title: Jaime Luengo Rozas
email: jluengorozas@gmail.com
description: >-
  Always looking for enthusiastic project to collaborate. Shoot me a email for
  any question about my work.
baseurl: ''
url: 'jaimeluengo.com'
github_username: jaimeluengo
linkedin: jaimeluengo
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-admin
