# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
#permalink:           pretty
#relative_permalinks: true

# Setup
title: Hello, world! I'm Jaime Luengo Rozas
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
#permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Jaime Luengo Rozas # add your name
author-img: jaime-luengo.jpg # add your photo
about-author: Practical theoritist, I like to implement. Always hungry to keep learning. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: jaimeluengo # add your Github handle
social-linkedin: jaime-luengo-rozas-b27572110 # add your Linkedin handle
social-email: # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: UA-121310230-1 # Google
paginate:            5

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-admin
# Custom vars
version:             1.0.0
